### ISSUE TITLE
Funnel adoptajdk visitors to adoptium

### ISSUE THREAD

**Issue by ge0ffrey** [adoptium/obsolete---adoptium.net#174]
Over the years, https://adoptopenjdk.net/ has gather a high google ranking (SEO) and captured many hearts and mind (great work!).
With the rebrand to Adoptium, these should all come to adoptium.net.

However...

The page adoptopenjdk.net currently looks like this:

![image](https://user-images.githubusercontent.com/176880/133601771-ca01914a-8b9f-4c3b-92f6-f705fd0ef873.png)

1) It's unclear if Adoptium is the new AdoptAJDK, or a fork.

2) Google rankings / SEO-wise, adoptopenjdk.net should just **flat out 301 redirect to Adoptium**, to recycle google rankings (and to avoid splitting them up between both - google ranking is a winner takes all system).

![image](https://user-images.githubusercontent.com/176880/133602144-2eeb0040-1ce4-483f-a502-fb1308ff8470.png)

**Comment by sxa** [comment]
A couple of points on this:
1. We are currently in a transition period so in order to avoid any breaks to people relying on the old adoptopenjdk.net web site and API we have redirects in place from adoptopenjdk to Temurin. The big blue download button on the adoptopenjdk.net site will actually provide you with the latest temurin build where one is available, but that will not be in place for ever and so we are encouraging people to start using the adoptium web site. The adoptium website will contain more than just Temurin so a straight redirect to the top level adoptium.net will probably not be the best option. The AdoptOpenJDK web site also providers older (out of support) java versions which will not be replicated at Adoptium.net, however for people who "just want to download java" we want them to start using adoptium.net going forward as these redirects are not expected to last forever.
2. As alluded to in the first point, not all things which were available at AdoptOpenJDK are available via Adoptium. Adoptium cannot distribute OpenJ9-based builds for legal reasons, so we don't want to suddenly lose people's ability to find those (similar to the Temurin API redirects, the AdoptOpenJDK website and API currently redirects to IBM Semeru builds of OpenJ9 where available). There are also other downloads that we had which are not available at Adoptium such as the [upstream builds](https://adoptopenjdk.net/upstream.html), [IcedTea-WEB](https://adoptopenjdk.net/icedtea-web.html) and [JDK Mission Control](https://adoptopenjdk.net/jmc.html) as well as the [Linux rpm/deb installers](https://adoptopenjdk.net/installation.html#installers) which are not yet available via Adoptium (we're [working on it](https://github.com/adoptium/installer/issues/330)) but are documented at AdoptOpenJDK, and we'd likely get many complaints if we just removed things without any notice or alternative.

I tried to cover a lot of this in the [Adoptium FAQ](https://adoptium.net/faq.html) (I need to update that as some things have changed since I wrote it - this is all somewhat dynamic!) which hopefully at least helps you understand why we are in the position we are at present.

**Comment by ge0ffrey** [comment]
Interesting challenges.
Maybe there are create ways to recycle the AdoptAJDK SEO ranking at the end of the transition period.

For example, 301 redirect from adoptajdk.net's main page to the adoptium's "tenerium download" page and have a link there "Looking for OpenJ9, go to adaptopjdk.net/openJ9" (a subpage that doesn't 301 redirect).

Not sure if it's worth it. Feel free to close this issue as "Won't fix".

**Comment by sxa** [comment]
I'm going to keep it open for a few days since I want to use this issue to cover updates to the FAQ and possibly including a redrafted version of what Iwrote above, but thanks for your understanding

**Comment by karianna** [comment]
@sxa can we close this now and maybe open up a new SEO-based one?

**Comment by sxa** [comment]
The [FAQ PR](https://github.com/adoptium/adoptium.net/pull/187) has seemingly been merged now, as has a change to [redirect the big blue download button](https://github.com/AdoptOpenJDK/openjdk-website/pull/1083) to make it clearer that people should be using Adoptium.net now, so I'm happy that this has been addressed now.
